zalando-nakadi/fahrschein

- .travis.yml
- src/main/java/org/zalando/fahrschein/InMemoryCursorManager.java
- src/main/java/org/zalando/fahrschein/StreamParameters.java
> Thread safe cursor manager

- src/main/java/org/zalando/fahrschein/BackoffException.java
- src/main/java/org/zalando/fahrschein/BackoffStrategy.java
- src/main/java/org/zalando/fahrschein/ExponentialBackoffStrategy.java
- src/main/java/org/zalando/fahrschein/NakadiClient.java
- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/main/java/org/zalando/fahrschein/NoBackoffStrategy.java
- src/test/java/org/zalando/fahrschein/salesorder/Main.java
> Refactor backoff strategy

- pom.xml
- src/main/java/org/zalando/fahrschein/Listener.java
- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/test/resources/log4j2.xml
> Allow custom parse error handling

- src/main/java/org/zalando/fahrschein/NakadiReader.java
> Retry connecting in case of read timeouts during json parser creation

- src/main/java/org/zalando/fahrschein/jdbc/JdbcCursorManager.java
- src/test/java/org/zalando/fahrschein/jdbc/JdbcCursorManagerIT.java
- src/test/java/org/zalando/fahrschein/jdbc/JdbcCursorManagerTest.java
> Support usage of PersistentCurosorManger with database schemas.

- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/main/java/org/zalando/fahrschein/ProblemHandlingClientHttpRequest.java
> Fix potential connection leaks

- pom.xml
@jhorstmann @lukasniemeier-zalando Please have a look.
> Skip Pre- and Post-Database-Processing if ITs are skipped.

- pom.xml
- src/main/java/org/zalando/fahrschein/NakadiClient.java
- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/main/java/org/zalando/fahrschein/NakadiReaderFactory.java
- src/main/java/org/zalando/fahrschein/metrics/DropwizardMetricsCollector.java
- src/main/java/org/zalando/fahrschein/metrics/MetricsCollector.java
- src/main/java/org/zalando/fahrschein/metrics/NoMetricsCollector.java
@jhorstmann @lukasniemeier-zalando @whiskeysierra 
I want to be able to live monitor the client. E.g. I want to be sure, keep alive events still arrive when my listener doesn't consume any events anymore.
Do you have a better idea to collect these metrics?
> Collect metrics

- src/main/java/org/zalando/fahrschein/domain/Partition.java
* Add `@ JsonCreator` to Partition class construtor to be able to parse it using jackson deserializer
> Add `@ JsonCreator` to Partition class construtor to be able to parse it using jackson deserializer

- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
> Unwrap all IOExceptions from MappingIterator

- src/main/java/org/zalando/fahrschein/NakadiReader.java
> Disable pretty printing of cursor header value

- src/main/java/org/zalando/fahrschein/NakadiReader.java
> Fail early with a ClassCastException

- src/main/java/org/zalando/fahrschein/CursorManager.java
- src/main/java/org/zalando/fahrschein/ManagedCursorManager.java
- src/main/java/org/zalando/fahrschein/NakadiClient.java
- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/main/java/org/zalando/fahrschein/StreamParameters.java
- src/main/java/org/zalando/fahrschein/domain/Cursor.java
- src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
> Ignore unknown properties and subscription api changes

- src/main/java/org/zalando/fahrschein/ManagedCursorManager.java
- src/main/java/org/zalando/fahrschein/domain/Cursor.java
> Wrap cursors in object when comitting

- src/main/java/org/zalando/fahrschein/domain/Subscription.java
> Do not require ParameterNames and JavaTime modules for subscription api

- src/main/java/org/zalando/fahrschein/NakadiClient.java
- src/main/java/org/zalando/fahrschein/NakadiReader.java
- src/main/java/org/zalando/fahrschein/domain/AbstractDataChangeEvent.java
- src/main/java/org/zalando/fahrschein/domain/DataChangeEvent.java
- src/main/java/org/zalando/fahrschein/domain/DataOperation.java
- src/main/java/org/zalando/fahrschein/domain/Metadata.java
- src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
This builds upon PR #93 by @mastersimon with some small refactorings and test for deserialization.
Fixes #93
> Generic data change event

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
> Check isInterrupted flag regularly also if no InterruptedException was thrown

- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/domain/SubscriptionRequest.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
> Support reading from the beginning in the subscription api

- fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
Fixes #138 
See nakadi api at https://github.com/zalando/nakadi/blob/R2017_02_13/api/nakadi-event-bus-api.yaml#L1328
> Fix Typo in metadata occurred_at

- fahrschein/src/main/java/org/zalando/fahrschein/EventPublishingException.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingClientHttpRequest.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java
- fahrschein/src/main/java/org/zalando/fahrschein/domain/BatchItemResponse.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
> Support publishing events

- README.md
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderCreatedEvent.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderPaymentAcceptedEvent.java
- fahrschein-redis/src/test/java/org/zalando/fahrschein/redis/CursorRedisSerializerTest.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java
- fahrschein/src/main/java/org/zalando/fahrschein/SubscriptionBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/domain/Cursor.java
- fahrschein/src/test/java/org/zalando/fahrschein/CursorManagerDefaultMethodsTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
The overloads for the `subscribe` method were getting a bit out of hand.
Also includes some small fixes to log the correct event name when subscribing to multiple events.
> SubscriptionBuilder

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
Alternative solution for #154 
@tmuehl can you please review?
> Make sure that response is closed on all exceptions

- fahrschein-inmemory/src/main/java/org/zalando/fahrschein/inmemory/InMemoryCursorManager.java
- fahrschein-jdbc/src/main/java/org/zalando/fahrschein/jdbc/JdbcCursorManager.java
- fahrschein-redis/src/main/java/org/zalando/fahrschein/redis/RedisCursorManager.java
- fahrschein/src/main/java/org/zalando/fahrschein/CursorManager.java
- fahrschein/src/main/java/org/zalando/fahrschein/DefaultErrorHandler.java
- fahrschein/src/main/java/org/zalando/fahrschein/ErrorHandler.java
- fahrschein/src/main/java/org/zalando/fahrschein/Listener.java
- fahrschein/src/main/java/org/zalando/fahrschein/ManagedCursorManager.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
Also remove unused and confusing `onError` method of `CursorManager`
> Separate error handler

- README.md
- fahrschein-example/pom.xml
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein-http-apache/pom.xml
- fahrschein-http-apache/src/main/java/org/zalando/fahrschein/http/apache/HttpComponentsClientHttpRequest.java
- fahrschein-http-apache/src/main/java/org/zalando/fahrschein/http/apache/HttpComponentsClientHttpRequestFactory.java
- fahrschein-http-apache/src/main/java/org/zalando/fahrschein/http/apache/HttpComponentsClientHttpResponse.java
- fahrschein-http-simple/pom.xml
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleBufferingClientHttpRequest.java
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleClientHttpRequestFactory.java
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleClientHttpResponse.java
- fahrschein-jdbc/pom.xml
- fahrschein-redis/pom.xml
- fahrschein/pom.xml
- fahrschein/src/main/java/org/zalando/fahrschein/AuthorizedClientHttpRequestFactory.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingClientHttpRequest.java
- fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingClientHttpRequestFactory.java
- fahrschein/src/test/java/org/zalando/fahrschein/ManagedCursorManagerTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/MockServer.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
- pom.xml
To work around spring trying to drain the connection on close. This is a slightly less radical version of #160 
Fixes #17 and #83
> Include our own ClientHttpRequestFactory implementations

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
> remove subscriptions from Nakadi

- fahrschein/src/main/java/org/zalando/fahrschein/ManagedCursorManager.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java
By wrapping the ClientHttpRequestFactory with problem handling and authorization if needed
Fixes #169
> Make ManagedCursorManager extensible

- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderCreatedEvent.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderEvent.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderPaymentAcceptedEvent.java
refactoring subscriptionMultipleEvents example
> example refactoring

- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderCreatedEvent.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderEvent.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderEventProcessor.java
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/domain/OrderPaymentAcceptedEvent.java
This moves the processing locic to a central place and allows the usage
of dependencies for handling events.
> Use double-dispatch in multi-event example

- fahrschein-jdbc/pom.xml
- fahrschein-jdbc/src/main/java/org/zalando/fahrschein/jdbc/TransactionalBatchHandler.java
- fahrschein-jdbc/src/test/java/org/zalando/fahrschein/jdbc/LocalPostgresConfiguration.java
- fahrschein-jdbc/src/test/java/org/zalando/fahrschein/jdbc/TransactionHandlerIT.java
- fahrschein/pom.xml
- fahrschein/src/main/java/org/zalando/fahrschein/BatchHandler.java
- fahrschein/src/main/java/org/zalando/fahrschein/DefaultBatchHandler.java
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
- pom.xml
> Allow wrapping event processing and commit in a transaction

- fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/HeadersImpl.java
- fahrschein-http-api/src/test/java/org/zalando/fahrschein/http/api/HeadersImplTest.java
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleBufferingRequest.java
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleRequestFactory.java
- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleResponse.java
- fahrschein/src/main/java/org/zalando/fahrschein/DefaultObjectMapper.java
> Use fixed length streaming mode and some other bugfixes

- fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleBufferingRequest.java
> Cannot write if do output is false

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java
- fahrschein/src/test/java/org/zalando/fahrschein/MockServer.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/ProblemHandlingRequestTest.java
> Do not ignore status 422 when creating subscription

- README.md
> #198 fix readme

- README.md
Closes #199 
If somebody knows how to formulate this better - I'm open for suggestions
> #199 change error handling description in readme

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
> Remember interrupted flag in case it gets cleared

- fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java
There were no existing tests for this part of the code. Do I need to still provide one?
Closes #208, Closes #209
> Fixed ZignAccessTokenProvider

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
> Log unexpected throwable before returning from NakadiReader

- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
- fahrschein/src/main/java/org/zalando/fahrschein/EqualJitterBackoffStrategy.java
- fahrschein/src/main/java/org/zalando/fahrschein/ExponentialBackoffStrategy.java
- fahrschein/src/main/java/org/zalando/fahrschein/FullJitterBackoffStrategy.java
- fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
Implementation of:
https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
> Equal & FullJitterBackoffStrategy

- fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
@zekefast @pc-alves @whiskeysierra please have a quick look
> Make Metadata and span ctx immutable

- MAINTAINERS
@jhorstmann here are the new maintainers for `fahrschein`.
Before we merge this PR, we would like to have a handover session if possible.
> Maintainers Class of 2022

- .github/workflows/ci.yml
- .github/workflows/maven-publish.yml
- pom.xml
Automate release of the project with Github Actios
> Issue 259 introduce release

- MAINTAINERS
- pom.xml
Update maintainers and correct scm information
> #259 Update maintainers list and scm information

- fahrschein-example/pom.xml
- pom.xml
Adds OWASP Dependency Check plugin for maven. 
* https://jeremylong.github.io/DependencyCheck/index.html
> Add CVE scanning & upgrade vulnerable libraries

- CONTRIBUTING.md
I used zalando/skipper as template, as I felt this mostly covered all
of the requirements. I haven't found any code formatting guidelines, so
this part is missing.
> Contribution guideline updated

- CODE_OF_CONDUCT.md
Add zalando standard CODE_OF_CONDUCT
> Add zalando standard CODE_OF_CONDUCT

- README.md
- pom.xml
Mentions how to run/skip integration tests. At the moment, Fahrschein integration tests do not work with PostgreSQL14.
> README.md: Describe local development

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
declare EventPublishingException in NakadiClient.publish
https://github.com/zalando-nakadi/fahrschein/issues/270
> declare EventPublishingException in NakadiClient.publish

- fahrschein-example/pom.xml
- fahrschein-http-apache/pom.xml
- fahrschein-http-api/pom.xml
- fahrschein-http-simple/pom.xml
- fahrschein-http-spring/pom.xml
- fahrschein-inmemory/pom.xml
- fahrschein-jdbc/pom.xml
- fahrschein-metrics-dropwizard/pom.xml
- fahrschein-redis/pom.xml
- fahrschein-test-support/pom.xml
- fahrschein-typeresolver/pom.xml
- fahrschein/pom.xml
- pom.xml
Preparation of next release `0.19.0`
> Prepare next release

- .github/workflows/maven-publish.yml
- pom.xml
Add missing environment variables
Skip integration tests
> Introduce missing variables and configurations

- .github/workflows/maven-publish.yml
> Re-add MAVEN_USERNAME and MAVEN_PASSWORD

- .github/workflows/maven-publish.yml
mistakenly deleted the server-id as well
> Re-add server-id

- fahrschein-example/pom.xml
- fahrschein-http-apache/pom.xml
- fahrschein-http-api/pom.xml
- fahrschein-http-simple/pom.xml
- fahrschein-http-spring/pom.xml
- fahrschein-inmemory/pom.xml
- fahrschein-jdbc/pom.xml
- fahrschein-metrics-dropwizard/pom.xml
- fahrschein-redis/pom.xml
- fahrschein-test-support/pom.xml
- fahrschein-typeresolver/pom.xml
- fahrschein/pom.xml
- pom.xml
> Release 0.19.0

- .github/workflows/maven-publish.yml
Use `maven_profiles` to specify the proper release profile
> ISSUE-259 Use maven profiles arg to specify the profile to use

- pom.xml
Drop nexus URL from plugin description
> ISSUE-259 Drop repository URL modification

- pom.xml
Re-introduce nexus url parameter again pointing to the right address
> ISSUE-259 Set the mandatory paramter pointing ot the right url

- fahrschein-e2e-test/pom.xml
- fahrschein-example/pom.xml
- fahrschein-http-apache/pom.xml
- fahrschein-http-api/pom.xml
- fahrschein-http-simple/pom.xml
- fahrschein-http-spring/pom.xml
- fahrschein-inmemory/pom.xml
- fahrschein-jdbc/pom.xml
- fahrschein-metrics-dropwizard/pom.xml
- fahrschein-redis/pom.xml
- fahrschein-test-support/pom.xml
- fahrschein-typeresolver/pom.xml
- fahrschein/pom.xml
- pom.xml
> Release 0.20.0

- docs/RELEASING.md
> Document release process

- fahrschein-e2e-test/pom.xml
- fahrschein-example/pom.xml
- fahrschein-http-apache/pom.xml
- fahrschein-http-api/pom.xml
- fahrschein-http-jdk11/pom.xml
- fahrschein-http-simple/pom.xml
- fahrschein-http-spring/pom.xml
- fahrschein-http-test-support/pom.xml
- fahrschein-inmemory/pom.xml
- fahrschein-jdbc/pom.xml
- fahrschein-metrics-dropwizard/pom.xml
- fahrschein-redis/pom.xml
- fahrschein-test-support/pom.xml
- fahrschein-typeresolver/pom.xml
- fahrschein/pom.xml
- pom.xml
* Document release process by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/309
* Remove log4j from project by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/306
* Cleanup deprecation warnings in tests by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/305
* Exception while the cursor is being committed by @a-liut in https://github.com/zalando-nakadi/fahrschein/pull/251
* Fixes CursorManager README example misleading by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/312
* JavaNet RequestFactory implementation by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/304
* Dependency cleanup by @otrosien in https://github.com/zalando-nakadi/fahrschein/pull/321
* Remove test code duplication by @otrosien in …
> Release 0.21.0

- fahrschein-e2e-test/pom.xml
- fahrschein-example/pom.xml
- fahrschein-http-apache/pom.xml
- fahrschein-http-api/pom.xml
- fahrschein-http-jdk11/pom.xml
- fahrschein-http-simple/pom.xml
- fahrschein-http-spring/pom.xml
- fahrschein-http-test-support/pom.xml
- fahrschein-inmemory/pom.xml
- fahrschein-jdbc/pom.xml
- fahrschein-metrics-dropwizard/pom.xml
- fahrschein-redis/pom.xml
- fahrschein-test-support/pom.xml
- fahrschein-typeresolver/pom.xml
- fahrschein/pom.xml
- pom.xml
Start develpment of 0.22.0-SNAPSHOT
> Start develpment of 0.22.0-SNAPSHOT

- README.md
- fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java
removing some leftovers after https://github.com/zalando-nakadi/fahrschein/pull/326
> Small pgsql/redis cleanup

- README.md
- gradle.properties
> Start 0.23.0 development

- README.md
> Document backoff strategies in README

- .github/workflows/ci.yml
> Run codecov with CI build

- .github/workflows/ci.yml
> Compare codecov with codacy

- gradle.properties
We want to move towards a 1.0 stable release of Fahrschein, in order to fork a 2.0 branch, and tackle breaking changes like 
https://github.com/zalando-nakadi/fahrschein/issues/314
> Start 1.0 development

- .github/workflows/ci.yml
- CONTRIBUTING.md
Adapt to the renamed main branch of the repository.
> Rename master -> main

- fahrschein/src/main/java/org/zalando/fahrschein/CursorManager.java
Closes #338
Signed-off-by: Oliver Trosien <oliver.trosien@zalando.de>
> Document CursorManager#onSuccess

- gradle.properties
Make 0.24.0 last release before 1.0.0
> Make 0.24.x last release line before 1.0.0

- gradle.properties
In case there is nothing left to fix, this can also become 1.0.0 later.
> Starting 0.24.1 development

- cve-suppressions.xml
This relates to https://github.com/jeremylong/DependencyCheck/issues/5502.
> Suppresses false-positive CVE-2022-45688

- README.md
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
- fahrschein/src/main/java/org/zalando/fahrschein/SubscriptionBuilder.java
- fahrschein/src/main/java/org/zalando/fahrschein/domain/Subscription.java
> Using Subscription Id created with EventTypeSubscription

- gradle.properties
* Step 1 of 2: Update release version in repository
* Step 2 of 2: Create a release in Github to trigger publishing of the maven artifact.
> Create 1.0.0 release

- gradle.properties
> Start 1.0.1 development

- README.md
- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
See https://github.com/zalando-nakadi/fahrschein/issues/298
> Retry initial connection

- cve-suppressions.xml
Another Spring CVE that does not apply to Fahrschein.
See https://nvd.nist.gov/vuln/detail/CVE-2023-20861
> Ignore CVE-2023-20861

- cve-suppressions.xml
We're not using Spring's SpEL expressions. See CVE-2023-20863 for more details.
> Suppress CVE-2023-20863

- fahrschein-opentelemetry/README.md
Fix example in OpenTelemetry README.md
> Fix example in OpenTelemetry README.md

- MAINTAINERS
- buildSrc/src/main/groovy/fahrschein.maven-publishing-conventions.gradle
Update MAINTAINERS based on recent contributions
> Update MAINTAINERS based on recent contributions

- build.gradle
- fahrschein-spring-boot-starter/build.gradle
> Minor gradle build polishing

- fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
- fahrschein/src/test/java/org/zalando/fahrschein/domain/MetadataTest.java
Fixes https://github.com/zalando-nakadi/fahrschein/issues/441
> Add partitionCompactionKey as Metadata attribute

- gradle.properties
> Release 2.0.0-RC4

- README.md
Update README references for example code
> Update README references for example code

- README.md
More README.md cleanups regarding retries
> More README.md cleanups regarding retries

- fahrschein-metrics-dropwizard/src/test/java/org/zalando/fahrschein/metrics/dropwizard/DropwizardMetricsCollectorTest.java
- fahrschein-metrics-micrometer/src/main/java/org/zalando/fahrschein/metrics/micrometer/MicrometerMetricsCollector.java
- fahrschein-metrics-micrometer/src/test/java/org/zalando/fahrschein/metrics/micrometer/MicrometerMetricsCollectorTest.java
Fixes #452, depends on #454
- Fixes a recursion bug in the micrometer metrics integration
- Adds more unit tests for both micrometer and dropwizard
> Fix stack overflow error in micrometer

- gradle.properties
> Release 2.0.0-RC5

- .github/workflows/ci.yml
- .github/workflows/cve-scan.yml
- .github/workflows/maven-publish.yml
Upgrade gradle in github actions to 8.5 (to align it with the gradle wrapper in the repo)
> Upgrade gradle in github actions

- gradle.properties
After 5 release candidates, we should be ready for a final release.
> Release 2.0.0

- gradle.properties
Bump version for the next release
> Bump version for the next release (2.0.1)

- fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
- fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
In case "alien" events pop up in Nakadi event type, it can't be parsed by the client and issues are raised by the EventReader. Information about the partition and offset are not logged out and troubleshooting it is quite difficult. Therefore this change identifies issues during parsing/reading of events and allows the read batch to finish it process/loop so the cursor information can be grabbed and printed out afterwards.
> Improve logging information for failed events during parsing.

- gradle.properties
Two pending changes justify a patch release: 
- Fix for CVE-2024-22243
- https://github.com/zalando-nakadi/fahrschein/pull/466
> Release 2.0.2
