zalando-nakadi/fahrschein

src/main/java/org/zalando/fahrschein/IOCallable.java
=> IOCallable does not need to wrap exceptions

src/main/java/org/zalando/fahrschein/metrics/LastActivityMetricsCollector.java, src/main/java/org/zalando/fahrschein/metrics/MultiplexingMetricsCollector.java
- `MultiplexingMetricsCollector`: To be able to register multiple `MetricCollector`s:
- `LastActivityMetricsCollector`: In the past we often wanted to build health checks to detect that Fahrschein doesn't consume any events anymore. The Problem with the Dropwizard metric library is that it uses decaying function such that a metric never reaches exact `0`. With this `MetricCollector` one can build alerts like "_Haven't consumed any event since 10 minutes_" and restart the consumer if necessary (sometimes just reconnect helped if the `ClientHttpRequest` stucked silently).
@jhorstmann @lukasniemeier-zalando
=> Provide additional MetricsCollectors

README.md, fahrschein/src/main/java/org/zalando/fahrschein/NakadiReader.java
so that read timeouts while determining the encoding of the event batch lead to automatic retry.
@danielrohe can you check if this fixes #123 and #124 ?
=> Lazily construct JsonParser

README.md, fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilder.java, fahrschein/src/main/java/org/zalando/fahrschein/StreamBuilders.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderTest.java
Example how #161 can already be achieved with the current code. Introduces new `runnable` method on `StreamBuilder` to simplify using it in a thread pool.
=> Stopping and resuming reader with executor

README.md
The builder method is (since 0.12.0) named `withRequestFactory`, not `withClientHttpRequestFactory`.
And the default implementation is `SimpleRequestFactory`, not `SimpleClientHttpRequestFactory`.
=> fix RequestFactory mentions in README

fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java
After addition of propagation support of Open Tracing's span context to Nakadi through `span_ctx` attribute in `metadata` we need to be able to reach span context in received events by using client libraries.
Changes in this pull request give ability to retrieve span context data as `Map<String, String>` through event's `getMetadata().getSpanCtx()`.
- Introduce new `Metadata` attribute `spanCtx`
- Modify `Metadata` constructors to initialize the attribute
- Add getter for the attribute
- Modify test `NakadiReaderDeserializationTest#shouldDeserializeBusinessEventMetadata` to check for empty span context (`null`) when it absent in JSON payload.
- Add test `NakadiReaderDeserializationTest#shouldDeserializeSpanCtxInBusinessEventMetadata` to check proper deserialization of JSON's span context …
=> Add support for Open Tracing's span context.

fahrschein-example/src/main/java/org/zalando/fahrschein/example/Main.java, fahrschein/src/main/java/org/zalando/fahrschein/AuthorizationBuilder.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java, fahrschein/src/main/java/org/zalando/fahrschein/SubscriptionBuilder.java, fahrschein/src/main/java/org/zalando/fahrschein/domain/Authorization.java, fahrschein/src/main/java/org/zalando/fahrschein/domain/Subscription.java, fahrschein/src/main/java/org/zalando/fahrschein/domain/SubscriptionRequest.java, fahrschein/src/test/java/org/zalando/fahrschein/ManagedCursorManagerTest.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java
Fixes #234
This is absolutely a must for environments that don't support creating unauthorized subscriptions.
Tested locally with the Zalando internal Nakadi, works good.
=> #234 - support authorization for subscriptions

fahrschein/src/main/java/org/zalando/fahrschein/AccessTokenProvider.java, fahrschein/src/main/java/org/zalando/fahrschein/AuthorizationProvider.java, fahrschein/src/main/java/org/zalando/fahrschein/AuthorizedRequestFactory.java, fahrschein/src/main/java/org/zalando/fahrschein/ManagedCursorManager.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java, fahrschein/src/test/java/org/zalando/fahrschein/AccessTokenProviderTest.java, fahrschein/src/test/java/org/zalando/fahrschein/AuthorizedRequestFactoryTest.java
Right now the `AuthorizedRequestFactory` is hardwired to `Bearer` authorization, by prefixing it to whatever the `AccessTokenProvider` provides. In this change we introduce a new `AuthorizationProvider` interface providing the whole authorization string, allowing users to choose freely.
* add new AuthorizationProvider interface providing full authorization string
* add adapter for AccessTokenProvider
* extend public interfaces with new provider
=> Allow any type of authorization type

.travis.yml, fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java, fahrschein/src/test/java/org/zalando/fahrschein/domain/MetadataTest.java
* added toString method for MetaData to get a string representation of such objects in logs
* added "dist: trusty" to .travis.yml to be able to use oraclejdk8 further. Otherwise we need to change jdk  to oraclejdk8, for example.
=> toString method for MetaData

.zappr.yaml
~~The current zappr configuration doesn't enforce 4-eyes principle, fixing it.~~
Apparently the current zappr configuration does seem to enforce 4-eyes as I cannot thumb-up my own PR. So, this commit is just cleaning up and inserting the zappr defaults, which should be: two thumbs-up needed by authorized members, but author can +1 himself.
=> Ensure 4-eyes principle

README.md, fahrschein-jdbc/src/main/java/org/zalando/fahrschein/jdbc/JdbcCursorManager.java, fahrschein-redis/src/main/java/org/zalando/fahrschein/redis/RedisCursorManager.java
Nakadi's low-level API has one use-case: if you always want to read a
topic from the beginning. This is incompatible with the idea of an
external persistant storage for offsets. If offset persistance is
needed, people should use the normal subscription APIs.
This commit marks the JDBC and Redis implementations as deprecated, so
that we can remove them in a future release.
Signed-off-by: Oliver <oliver.trosien@zalando.de>
=> Deprecate external Cursor management

fahrschein/src/test/java/org/zalando/fahrschein/MockServer.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiReaderDeserializationTest.java, fahrschein/src/test/java/org/zalando/fahrschein/StreamParametersTest.java
Deprecations removal:
* <T>assertThat(T,org.hamcrest.Matcher<? super T>) in org.junit.Assert has been deprecated
=> Cleanup deprecation warnings in tests

fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java
close #250.
The solution adopted in this PR is to allow `fahrschein` to parse the content of the response from Nakadi even if the response ContentType is null.
With this fix, the `NullPointerException` is avoided. A different exception might be thrown during the parsing but such exception will be caught by the surrounding try-catch as usual.
=> Exception while the cursor is being committed

README.md
Looking at 0b1aaa01d7dfbc6b0189ba6356f24199dd4bca82 where the relevant changes were introduced, I guess this is how the resulting code should look like.
Closes #299
=> Fixes CursorManager README example misleading

README.md, fahrschein-e2e-test/pom.xml, fahrschein-e2e-test/src/test/java/org/zalando/fahrschein/http/AbstractRequestFactoryTest.java, fahrschein-e2e-test/src/test/java/org/zalando/fahrschein/http/jdk11/IdentityEncodingJavaNetNakadiClientTest.java, fahrschein-e2e-test/src/test/java/org/zalando/fahrschein/http/jdk11/JavaNetNakadiClientTest.java, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/Response.java, fahrschein-http-jdk11/pom.xml, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/HttpRequestBuilderAdapter.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetBufferingRequest.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetRequestFactory.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetResponse.java, fahrschein-http-jdk11/src/test/java/org/zalando/fahrschein/http/jdk11/JavaNetRequestFactoryTest.java, pom.xml
A new zero-dependency RequestFactory implementation, based on the [java.net HttpClient](https://openjdk.java.net/groups/net/httpclient/intro.html) coming with JDK11+.
Work Packages:
Open Questions:
1. Do we want to make this a drop-in replacement for the old http-simple?
2. Should we mark this API as "experimental" in the first release? If so, how?
3. Do we offer this module before switching the general Fahrschein baseline to JDK11?
4. There will be conflicts with https://github.com/zalando-nakadi/fahrschein/pull/311 - which to merge first, and which to rebase?
=> JavaNet RequestFactory implementation

fahrschein-e2e-test/pom.xml, fahrschein-http-apache/pom.xml, fahrschein-jdbc/pom.xml, fahrschein-redis/pom.xml, fahrschein-redis/src/test/java/org/zalando/fahrschein/redis/RedisCursorManagerIT.java, pom.xml
* Ensures jcl-over-slf4j in all cases
* Aligns and bumps mockito version
* Aligns and bumps HikariCP
* Bumps spring to avoid CVE vulnerability warning
* Bumps redis and spring-data-redis
=> Dependency cleanup

README.md, fahrschein-http-apache/src/main/java/org/zalando/fahrschein/http/apache/HttpComponentsRequest.java, fahrschein-http-api/pom.xml, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/ContentEncoding.java, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/Headers.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetBufferingRequest.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetResponse.java, fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleBufferingRequest.java, fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleResponse.java, fahrschein-http-spring/src/main/java/org/zalando/fahrschein/http/spring/RequestAdapter.java, fahrschein-http-test-support/src/main/java/org/zalando/fahrschein/http/test/AbstractRequestFactoryTest.java, fahrschein/src/main/java/org/zalando/fahrschein/IdentityAcceptEncodingRequestFactory.java, fahrschein/src/test/java/org/zalando/fahrschein/IdentityAcceptEncodingRequestFactoryTest.java
Adds ZStandard compression support, based on the same library that also Nakadi is using (com.github.luben:zstd-jni).
* Added compression support for both GZip and ZStandard
* Limits compression to `POST` requests, as [Nakadi only supports it for those](https://github.com/zalando/nakadi/blob/master/core-common/src/main/java/org/zalando/nakadi/util/CompressionBodyRequestFilter.java#L52). Luckily Fahrschein does not send any PATCH or PUT anyway. 
* Introduces new Header constants for Content-Encoding and Accept-Encoding.
Closes #310
=> Adds ZStandard compression support

fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetBufferingRequest.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetHeadersDelegate.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetResponse.java, fahrschein-http-jdk11/src/test/java/org/zalando/fahrschein/http/jdk11/JavaNetHeadersDelegateTest.java
Introduces a delegate class to avoid copying of all headers.
Also throws 'UnsupportedOperationExceptions' in case of misuse.
=> JDK11 client: Avoid copying of headers

fahrschein/src/main/java/org/zalando/fahrschein/EventPublishingException.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java
Start documenting public classes and methods with Javadoc
Closes #241 , closes #131
=> Add documentation

fahrschein/pom.xml
Although technically correct (there is no dependency at build time),
we want to expose the SimpleRequestFactory to users at their compile-time (!), which is
prohibited by gradle's interpretation of the pom.xml, if a dependency
is marked as runtime.
https://github.com/zalando-nakadi/fahrschein/issues/328
In a closer look, this is a valid interpretation of [the spec](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope):
**runtime** This scope indicates that the dependency is not required for compilation, but is for execution. Maven includes a dependency with this scope in the runtime and test classpaths, but not the compile classpath.
=> Reverts the fahrschein-http-simple to runtime dependency

fahrschein-example/build.gradle, fahrschein-metrics-dropwizard/build.gradle, fahrschein/build.gradle
In PR #323 we raised the topic of majorly outdated dependencies of fahrschein. These include:
io.dropwizard.metrics:metrics-core (3.1.2 -> 4.2.9)
org.zalando:jackson-datatype-money (0.6.0 -> 1.3.0)
com.jayway.jsonpath:json-path (2.2.0 -> 2.7.0)
Closes #334
=> Upgrade dependencies: dropwizard-metrics, jackson-datatype-money, json-path

.github/workflows/cve-scan.yml, README.md, build.gradle, cve-suppressions.xml, gradle.properties
Changes:
* Bumps dependencycheck plugin to the latest
* Bumps Jackson to 2.13.3 (CVE-2020-36518)
* Bumps Spring to 5.3.20 - not necessarily related to CVE-2016-1000027 as that is a false positive
* Ignores CVE-2016-1000027, CVE-2020-29582 and CVE-2022-24329 in scan, see
cve-supressions.xml
* Makes build failure stricter, now triggering on CVE score 5 and above
(only works if we specify the score as number, not as string!)
* Speeds up CVE scan by removing redundant report generation for all subprojects, and avoids scanning for DLL/EXE based vulnerabilities.
Test by running `./gradlew :dependencyCheckAggregate` locally.
=> Analyses the CVE report, upgrades vulnerable dependencies and suppresses false-positives

README.md, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/Headers.java, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/UserAgent.java, fahrschein-http-api/src/test/java/org/zalando/fahrschein/http/api/UserAgentTest.java, fahrschein-http-api/src/test/resources/fahrschein.properties, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetBufferingRequest.java, fahrschein-http-test-support/src/testFixtures/java/org/zalando/fahrschein/http/test/AbstractRequestFactoryTest.java, fahrschein/build.gradle, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java, fahrschein/src/main/java/org/zalando/fahrschein/UserAgentRequestFactory.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java, fahrschein/src/test/java/org/zalando/fahrschein/UserAgentRequestFactoryTest.java
We would like to have an easy way to get some statistics around Fahrschein usage in general, and which versions, which JDK version, and via which HTTP client implementation specificially, in order to a) justify the time we're spending on the library, b) get more insights about builder behaviour. The header should be set by default (not overridable initially).
**Format**
"Fahrschein/" [FahrscheinVersion] " (" [HttpClient] "; " [Java Version] ("; " [Additional Property])* ")"
**Examples**
User-Agent: Fahrschein/0.22.0 (Simple; Java11)
User-Agent: Fahrschein/0.22.0 (ApacheHttpClient; Java8)
User-Agent: Fahrschein/0.22.0 (JavaNet; Java17; experimental-features=a,b,c)
User-Agent: Fahrschein/0.22.0 (Spring; Java8; Kotlin)
Closes https://github.com/zalando-nakadi/fahrschein/issues/327
=> Add Fahrschein User-Agent to Nakadi requests

README.md, build.gradle, buildSrc/src/main/groovy/fahrschein.java-conventions.gradle, fahrschein-e2e-test/build.gradle
* Adds jacoco-report-aggregation plugin as described in
https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_standalone.html
* Documents unit test coverage integration in README.md, consistently using the parent task "check" instead of "test"
* Marks fahrschein-e2e-test as IntegrationTest type
=> Aggregate jacoco test reports

build.gradle
Disable analyzers which don't matter to Fahrschein, according to this list:
https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
Many analyzers are auto-enabled, including RetireJS, a javascript analyzer. The RetireJS analyzer contained an invalid rule in master (2) (3), which got pulled in by the CVE scan, this broke the nightly CVE scan (1). 
1. https://github.com/zalando-nakadi/fahrschein/runs/7491798097?check_suite_focus=true
2. Broken here: https://github.com/RetireJS/retire.js/commit/60ffbeb1523c503da886b2a47b39551697ed06c8
3. Fixed shortly after: https://github.com/RetireJS/retire.js/commit/7007575f637b840016edf8a9512d608f00795b1b
=> Disable irrelevant CVE analyzers

fahrschein-http-apache/src/main/java/org/zalando/fahrschein/http/apache/HttpComponentsResponse.java, fahrschein-http-api/src/main/java/org/zalando/fahrschein/http/api/StreamUtils.java, fahrschein-http-jdk11/src/main/java/org/zalando/fahrschein/http/jdk11/JavaNetResponse.java, fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleBufferingRequest.java, fahrschein-http-simple/src/main/java/org/zalando/fahrschein/http/simple/SimpleResponse.java
The HTTP client facade code is original from spring, and the code for closing has diverged since. They have introduced a bug-fix to ensure that the InputStreams are properly drained, so the connections can be given back to the connection pools without resource leaks.
Closes #303
Changes:
* New StreamUtils helper class with static method to "drain"
* Calling drain() in fahrschein-http-simple and fahrschein-http-jdk11
* Slight refactoring of the apache client, to capture its InputStream for draining.
=> Drain InputStream on closing

README.md
Remove the outdated documentation in the readme file, which is about how to handle errors using `withErrorHandler()` which is removed in PR #205
=> Remove outdated documentation to handle errors

fahrschein-example/src/main/java/org/zalando/fahrschein/example/ProducerExample.java
Fix forbiddenApi usage of DateTime.now in fahrschein-example. Missed because I didn't rebase the forbiddenApis change before merging.
=> Fix forbiddenApi usage of DateTime.now in fahrschein-example

fahrschein-e2e-test/build.gradle, fahrschein-example/build.gradle, fahrschein-typeresolver/build.gradle, fahrschein/build.gradle, gradle.properties
* https://nvd.nist.gov/vuln/detail/CVE-2022-42003 - In FasterXML jackson-databind before 2.14.0-rc1, resource exhaustion can occur because of a lack of a check in primitive value deserializers to avoid deep wrapper array nesting, when the UNWRAP_SINGLE_VALUE_ARRAYS feature is enabled. Additional fix version in 2.13.4.1 and 2.12.17.1
* https://nvd.nist.gov/vuln/detail/CVE-2022-42004 - In FasterXML jackson-databind before 2.13.4, resource exhaustion can occur because of a lack of a check in BeanDeserializer._deserializeFromArray to prevent use of deeply nested arrays. An application is vulnerable only with certain customized choices for deserialization.
Only jackson-databind got updated to 2.13.4.2. For maximum consistency, we're bumping the other jackson modules to 2.13.4.
Caught by …
=> Fixes Jackson Vulnerabilities: CVE-2022-42003, CVE-2022-42004

MAINTAINERS
Othon will no longer be a maintainer of Fahrschein after switching back to the management track at Zalando.
=> Removing Othon Crelier from the maintainers' list

build.gradle
Nightly CVE scan fails with this error:
```
One or more dependencies were identified with known vulnerabilities in fahrschein-parent:
commons-codec-1.11.jar (pkg:maven/commons-codec/commons-codec@1.11, cpe:2.3:a:apache:commons_net:1.11:*:*:*:*:*:*:*) : CVE-2021-37533
commons-logging-1.2.jar (pkg:maven/commons-logging/commons-logging@1.2, cpe:2.3:a:apache:commons_net:1.2:*:*:*:*:*:*:*) : CVE-2021-37533
```
Both vulnerabilities affect commons-net, so these are false positives.
=> Fix false CVE positive (by upgrading the dependencycheck plugin)

README.md, fahrschein-example/src/main/java/org/zalando/fahrschein/example/ConsumerExample.java, fahrschein-example/src/main/java/org/zalando/fahrschein/example/ProducerExample.java, fahrschein-example/src/main/resources/nakadi-token-secret, fahrschein/src/main/java/org/zalando/fahrschein/PlatformAccessTokenProvider.java, fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java, fahrschein/src/test/java/org/zalando/fahrschein/PlatformAccessTokenProviderTest.java, fahrschein/src/test/resources/meta/credentials/nakadi-token-secret
Our default authorization provider ZignAccessTokenProvider.java is outdated and the usage of zign is not recomended anymore by default.
In this PR I have introduced support for [Zalando's platform IAM](https://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/zalando-iam.html) and we could replace ZignAccessTokenProvider with this new integration.
See https://github.com/zalando-nakadi/fahrschein/issues/381
=> Add support for zalando platform IAM

fahrschein-opentelemetry/src/main/java/org/zalando/fahrschein/opentelemetry/InstrumentedPublishingHandler.java, fahrschein-opentelemetry/src/test/java/org/zalando/fahrschein/opentelemetry/InstrumentedPublishingHandlerTest.java, fahrschein-opentracing/src/main/java/org/zalando/fahrschein/opentracing/InstrumentedPublishingHandler.java, fahrschein-opentracing/src/test/java/org/zalando/fahrschein/opentracing/InstrumentedPublishingHandlerTest.java, fahrschein/src/main/java/org/zalando/fahrschein/EventPublishingHandler.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
So that event publishing handlers do not interact with one another unexpectedly.
- Event publishing handlers are called in reverse order onError and afterPublish
- afterPublish is always called regardless of error (finally block) 
- every handler's afterPublish is ensured to be called by adding individual try-catch blocks
- API docs updated
=> WIP Reverse after and error handler calls

README.md
* adds mandatory subscription authorization section (closes #379)
* moves low-level API down
* creates publishing documentation section
* Fixes header ordering
* removes `final` from examples to reduce the syntactic noise
=> README: Restructuring

README.md
Please see https://github.com/zalando-nakadi/fahrschein/issues/392
What has been done ? 
Updated the comparison section 
- nakadi-java supports gzip compression on publishing
- Added some details on metric collection
=> Update comparison with nakadi-java

cve-suppressions.xml
CVE-2023-35116 is filed as false positive, according to the Jackson project maintainers. 
See https://github.com/FasterXML/jackson-databind/issues/3972
=> False positive: CVE-2023-35116

fahrschein/src/main/java/org/zalando/fahrschein/PlatformAccessTokenProvider.java, fahrschein/src/test/java/org/zalando/fahrschein/PlatformAccessTokenProviderTest.java, fahrschein/src/test/resources/meta/credentials/whitespace-newline-token-secret
Trim the authorization token to remove all leading and trailing whitespaces and new line characters from the token.
Closes https://github.com/zalando-nakadi/fahrschein/issues/398
=> Trim auth token

fahrschein-http-jdk11/build.gradle, fahrschein-http-spring/build.gradle, fahrschein-spring-boot-starter/build.gradle, gradle.properties
Upgrade to Spring6 and Spring Boot 3.
Thus, we decided to upgrade the JDK target to java17 for the whole project, which justifies a 2.0.0 release.
- Bumps baseline JDK to 17
- Sets default dependency for spring framework to 6
- Sets default dependency for spring-boot to 3
- Bumps the version to 2.0.0-RC1
=> Upgrade Spring dependencies and jdk target

fahrschein-spring-boot-starter/build.gradle, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/config/Ratio.java, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/config/Registry.java, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/config/TimeSpan.java, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/NakadiClientsPostProcessor.java, fahrschein-spring-boot-starter/src/test/java/org/zalando/spring/boot/fahrschein/nakadi/RegistryTest.java, fahrschein-spring-boot-starter/src/test/java/org/zalando/spring/boot/fahrschein/nakadi/config/properties/ConsumerConfigTest.java
Trying to reduce the amount of dependencies. The usage of guava in the spring-boot-starter was minimal, and can be replaced by a few lines of static code.
- use the already copied "checkArgument" from the core fahrschein module
- replace list functions with ones from Java17
- re-implement camel case and hyphen case conversions with custom implementations (+ tests)
- remove dependency from build.gradle
=> Remove guava from spring-boot-starter

README.md, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java
Adds @ePaul 's nice assessment of the status quo to the API docs.
Relates to #415
=> Document Nakadi Publishing failure handling

fahrschein-spring-boot-starter/build.gradle, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/ObjectMapperFactory.java
The ObjectMapper modules used for Fahrschein can be dicovered from the classpath. This avoids bloating fahrschein dependencies with potential use-cases like kotlin.
Closes #419
=> Remove kotlin dependency & discover jackson modules via classpath introspection

README.md
Removed false information from the doc
Reopened #422 from @adyach from the fahrschein repo.
=> removed wrong documentation wrt failure handling

README.md, fahrschein/src/main/java/org/zalando/fahrschein/EventPersistenceException.java, fahrschein/src/main/java/org/zalando/fahrschein/EventPublishingException.java, fahrschein/src/main/java/org/zalando/fahrschein/EventValidationException.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClient.java, fahrschein/src/main/java/org/zalando/fahrschein/ProblemHandlingRequest.java, fahrschein/src/main/java/org/zalando/fahrschein/domain/BatchItemResponse.java, fahrschein/src/test/java/org/zalando/fahrschein/NakadiClientTest.java, fahrschein/src/test/java/org/zalando/fahrschein/ProblemHandlingRequestTest.java
When publishing batches, Nakadi can return partial success. So far, we throw an `EventPublishingException`, independently of a validation vs. persistence error, and we  only include the failed BatchItemResponse entries. This means without event-id correlation locally it is impossible for teams to figure out which items from the batch need retrying. It also not obvious from the error, if the batch can be retried or not.
- Removes the filtering for only failed events when crafting the EventPublishingException
- Introduces subclasses for validation vs. persistence errors: `EventPersistenceException` for persistence failures which can be retried, `EventValidationException` for validation errors which need fixing on the client side and should not be retried.
- Adapts the documentation in the …
=> Allow clients to correctly handle partial publishing failures

fahrschein/src/main/java/org/zalando/fahrschein/domain/Metadata.java, fahrschein/src/test/java/org/zalando/fahrschein/domain/MetadataTest.java
This PR is adding the equals and hashcode methods implementations. It's a fix to the https://github.com/zalando-nakadi/fahrschein/issues/417 issue.
Reopened https://github.com/zalando-nakadi/fahrschein/pull/418 from the main fahrschein repository.
=> Implement equals and hashcode for Metadata.

fahrschein/src/main/java/org/zalando/fahrschein/StreamParameters.java, fahrschein/src/test/java/org/zalando/fahrschein/StreamParametersTest.java
- Supports stream parameter "batch_timespan" (closes #431)
- updates and add API documentation based on the latest API docs from Nakadi, incl. documentation of defaults
- Removes client-side validation of parameters (duplicates what the server will reject anyway)
- Removes an outdated comment from 2017 about a "silent bug". Nowadays Nakadi rejects a batch_limit of 0. (Verified and tested with Nakadi team)
=> StreamParameters refresher (documentation + new parameter support)

.github/workflows/ci.yml, README.md, fahrschein-e2e-test/src/test/java/org/zalando/fahrschein/e2e/NakadiClientEnd2EndTest.java, fahrschein-typeresolver/src/test/java/org/zalando/fahrschein/typeresolver/MetadataTypeResolverTest.java, fahrschein/src/main/java/org/zalando/fahrschein/DefaultObjectMapper.java, fahrschein/src/main/java/org/zalando/fahrschein/NakadiClientBuilder.java
The next version of Jackson is going to remove this property, which will make Fahrschein fail (see current ci-latest build workflows)
- https://github.com/FasterXML/jackson-databind/commit/d7a1efc7f45af4f56c0df4eccb0244418b6428bb
- https://github.com/zalando-nakadi/fahrschein/actions/runs/6639117822/job/18036824456
=> Remove deprecated Jackson 2.7 property CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

fahrschein-spring-boot-starter/README.md, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/config/TimeSpan.java, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/FahrscheinNakadiConsumer.java, fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/properties/StreamParametersConfig.java, fahrschein-spring-boot-starter/src/test/java/org/zalando/spring/boot/fahrschein/nakadi/ApplicationTest.java, fahrschein-spring-boot-starter/src/test/java/org/zalando/spring/boot/fahrschein/nakadi/config/TimeSpanTest.java, fahrschein-spring-boot-starter/src/test/java/org/zalando/spring/boot/fahrschein/nakadi/config/properties/ConsumerConfigTest.java, fahrschein-spring-boot-starter/src/test/resources/application.yml
Closes #429 
- makes time-based stream parameters batchFlushTimeout, streamTimeout, commitTimeout and batchTimespan of type timespan in the yaml configuration
- allows fallback to int-values, assuming "seconds" as unit (but emitting a [warning in the logs](https://github.com/zalando-nakadi/fahrschein/pull/433/files#diff-dfc37828957b018ab4ffca16b96db55e9b9bea7c277738346686dfcb391a49a6R60))
=> Consistency in stream parameters support for spring boot

fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/RequestFactories.java
Fixes  #435
The `ClientHttpRequestFactories` from Spring defaults to using Apache HttpClient 5.x (which we haven't tested our stack against) if it exists on the classpath. This HTTP client has two implementations, a streaming and a buffering one. We picked the wrong one - we need to pick buffering, not streaming, because we are calling getBody() to access the full content of the response body.
There is a backwards-compatible implementation which gets picked when you set `buffering=true`.
=> Spring-boot request factory: don't use streaming but buffering implementation

README.md
Update README code example for publishing with retry. We decided against injecting retry functionality by default.
=> Update README code example for publishing with retry.

fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/FahrscheinNakadiConsumer.java
Spring Boot: FahrscheinNakadiConsumer ignores consumer properties when subscription-id is not provided https://github.com/zalando-nakadi/fahrschein/issues/450
Contributed by @levabski
Supersedes  #451 (needed to rebase PR)
=> Spring Boot: Add Subscription config properties when subscription-by-id is not provided

.github/workflows/ci.yml
There are security constraints so that we cannot use a secret in github actions from forks. This makes the codacy step fail.
- Makes the execution of codacy conditional to only PRs from non-forks.
- Allowing exposure of secrets to PRs from forks can only be org-centrally enabled. If we had this enabled, and manual approval of running Github workflows for forks, we would be good. But it's unlikely to happen due to risks of exposing sensitive secrets.
=> Skip codacy check from forks

fahrschein-spring-boot-starter/src/main/java/org/zalando/spring/boot/fahrschein/nakadi/config/CursorManagerFactory.java
Fahrschein tries to add authorisation to requests when committing cursors even if OAuth is disabled.
This leads to errors such as:
```
java.nio.file.NoSuchFileException: /meta/credentials/nakadi-token-secret
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261) ~[na:na]
at java.base/java.nio.file.Files.newByteChannel(Files.java:379) ~[na:na]
at java.base/java.nio.file.Files.newByteChannel(Files.java:431) ~[na:na]
at java.base/java.nio.file.Files.readAllBytes(Files.java:3268) …
```
=> Fix Fahrschein using invalid OAuth configs when committing cursors
